WebWinkelGroep5/WebWinkelGroep5/Controllers/BestellingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebWinkelGroep5.Models;
using System.Net.Mail;

namespace WebWinkelGroep5.Controllers
{
    public class BestellingController : Controller
    {
        BestellingModel bestelling;
        //
        // GET: /Default1/

        public ActionResult Index()
        {
            return View();
        }

         public ActionResult BestellingenOverzicht()
        {
            List<BestellingStatus> bestelling = DatabaseController.GetBestellingen();
            return View();
        }
        
        public ActionResult WijzigBestellingStatus(int bestellingId)
        {
            try
            {
                BestellingStatus bestelling = DatabaseController.GetBestelling(bestellingId);
                return View();
            }
            catch (Exception e)
            {
                ViewBag.FoutMelding("Er is iets fout gegaan: " + e);
                return View();
            }
        }

        [HttpPost]
        public ActionResult WijzigBestellingStatus(BestellingStatus bestelling)
        {
            try
            {
                DatabaseController.WijzigBestelling(bestelling);
                return RedirectToAction("BestellingenOverzicht", "Product");
            }
            catch (Exception e)
            {
                ViewBag.FoutMelding("Er is iets fout gegaan: " + e);
                return View();
            }
        }

    

        [HttpPost]
        private void SendMail(WebWinkelGroep5.Models.MailModel _objModelMail)
        {
                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Host = "smtp.googlemail.com";
                smtpClient.Port = 587;
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Credentials = new System.Net.NetworkCredential("wooods-info@compuboot.in", "Wooods123");
                smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtpClient.EnableSsl = true;
                MailMessage mail = new MailMessage();

                //Setting From , To and CC
                mail.To.Add(_objModelMail.To);
                //mail.From = new MailAddress("wooods-info@compuboot.in");
                mail.Subject = _objModelMail.Subject;
                string Body = _objModelMail.Body;
                mail.Body = mail.From + "<br><br>" + Body;
                mail.IsBodyHtml = true;
                smtpClient.Send(mail);
        }


        public ActionResult MaakBestelling()
        {
            bestelling = new BestellingModel();
            bestelling.userId = DatabaseController.getUserId((String)Session["Username"]);
            bestelling.fromWinkelmandModel((WinkelmandModel)Session["Winkelmand"]);
            int bestellingId = DatabaseController.getNextBestellingId();
            bestelling.bestellingId = bestellingId;
            Session["BestellingId"] = bestellingId;
            foreach(WinkelmandItemModel m in bestelling.items)
            {
                DatabaseController.addBestellingLine(bestellingId, m.productId, m.amount, bestelling.userId);
            }
            return View(bestelling);
        }

        public ActionResult setGegevens(String bedrijfsnaam, String voornaam, String naam, String adres, String postcode, String land, String stad, String tel)
        {
            bestelling = new BestellingModel();
            DatabaseController.setUserDetails(voornaam + " " + naam, adres, stad, postcode, tel, (String)Session["Username"]);

            bestelling.items = DatabaseController.getBestelling((int)Session["BestellingId"]);

            return View(bestelling);
        }


    }
}

WebWinkelGroep5/WebWinkelGroep5/Views/Bestelling/BestellingenOverzicht.cshtml
@model List<WebWinkelGroep5.Models.BestellingStatus>

@{
    ViewBag.Title = "BestellingenOverzicht";
}

<h2>BestellingenOverzicht</h2>
Uw huidige bestellingen:
<hr />

@if (@ViewBag.FoutMelding != null)
{
    <span style="color:Red"> @ViewBag.FoutMelding </span>
}
@if (Model != null)
{
    <table id="hor-minimalist-b">
        <thead>
            <tr>
                <th>BestellingID</th>
                <th>GebruikerID</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>@Model[i].bestellingId</td>
                    <td>@Model[i].userId</td>
                    <td>@Model[i].bestellingStatus</td>

                    <td>@Html.ActionLink("Update", "WijzigBestellingStatus", new { bestellingId = @Model[i].bestellingId })</td>
                </tr>
            }
        </tbody>
    </table>
}

<hr />

WebWinkelGroep5/WebWinkelGroep5/Views/Bestelling/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>document.title = "Home"</script>
<h2>Index</h2>

WebWinkelGroep5/WebWinkelGroep5/Views/Bestelling/MaakBestelling.cshtml
@model WebWinkelGroep5.Models.BestellingModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>document.title = "Gegevens"</script>
<h2>MaakBestelling</h2>
@{
    if (Model != null)
    {
        List<WebWinkelGroep5.Models.WinkelmandItemModel> items = Model.items;
        foreach (WebWinkelGroep5.Models.WinkelmandItemModel item in items)
        {
            <h3>@(item.amount)x @WebWinkelGroep5.Controllers.DatabaseController.getProductName(item.productId) a @(WebWinkelGroep5.Controllers.DatabaseController.getProductPrice(item.productId) * item.amount)</h3>
        }
    }
}

<h2 align="center"> Contactgegevens</h2>
<form action="../Bestelling/setGegevens" method="post">
    <fieldset>
        @using (Html.BeginForm())
        {
            <p>Bedrijfsnaam</p>
            <input id="bedrijfsnaam" type="text">


            <p>Voornaam</p>
            <input id="voornaam" type="text">



            <p>Naam</p>
            <input id="naam" type="text">



            <p>Adres</p>
            <input id="adres" type="text">



            <p>Postcode</p>
            <input id="postcode" type="text">



            <p>Land</p>
            <input id="land" type="text">



            <p>Telefoon nummer</p>
            <input id="tel" type="text">


            @Html.ValidationSummary()
            <p>E-mailadres: </p>
            <p>@Html.TextBoxFor(m => m.To)</p>



            <input id="userid" type="hidden" value="@Model.userId">
            <!--<input id="userid" type="hidden" value="@Model.bestellingId">-->



            <input value="Verstuur" type="submit" />
        }
    </fieldset>

    <input type="radio" id="man" name="sex" value="male" checked>ja
    <input type="radio" name="sex" value="female">nee

    <br>Wilt u een bevestiging?




</form>

WebWinkelGroep5/WebWinkelGroep5/Views/Bestelling/SetGegevens.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>document.title = "Bestelling geplaatst"</script>

<h2>Bestelling geplaatst</h2>
Uw bestelling is geplaatst. Bedankt voor uw aankoop.

WebWinkelGroep5/WebWinkelGroep5/Views/Bestelling/WijzigBestellingStatus.cshtml
@model WebWinkelGroep5.Models.BestellingStatus

@{
    ViewBag.Title = "WijzigBestellingStatus";
}

<h2>WijzigBestellingStatus</h2>

@using (Html.BeginForm("WijzigBestellingStatus", "Bestelling"))
{
    @Html.ValidationSummary(true)

    <div class="editor-label">
        Status
    </div>
    @Html.HiddenFor(model => model.bestellingId)
    <div class="editor-field">
        @Html.DropDownListFor(model => model.BestellingStatus, Enum.GetValues(typeof(WebWinkelGroep5.Models.BestellingS)).Cast<WebWinkelGroep5.Models.BestellingS>().Select(v => new SelectListItem
       {
           Text = v.ToString().Replace("_", " "),
           Value = ((int)v).ToString()
       }), "[Select]")
        @Html.ValidationMessageFor(model => model.BestellingStatus)

    </div>

    <p>
        <input type="submit" value="Wijzig" />
    </p>
}

WebWinkelGroep5/WebWinkelGroep5/Views/Bestelling/showNewBestelling.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>document.title = "Uw bestelling"</script>
<h2>Uw nieuwe bestelling:</h2>
@{
    if (Model != null)
    {
        List<WebWinkelGroep5.Models.WinkelmandItemModel> items = Model.items;
        foreach (WebWinkelGroep5.Models.WinkelmandItemModel item in items)
        {
            <h3>@(item.amount)x @WebWinkelGroep5.Controllers.DatabaseController.getProductName(item.productId) a @(WebWinkelGroep5.Controllers.DatabaseController.getProductPrice(item.productId) * item.amount)</h3>
        }
    }
}