WebWinkelGroep5/WebWinkelGroep5/Controllers/SendMailerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace WebWinkelGroep5.Controllers
{
    public class SendMailerController : Controller
    {
        //
        // GET: /SendMail/

        public ActionResult mailtest()
        {
            return View();
        }
        [HttpPost]
        public ViewResult mailtest(WebWinkelGroep5.Models.MailModel _objModelMail)
        {
            if (ModelState.IsValid)
            {
                //SmtpClient smtpClient = new SmtpClient("smtp.googlemail.com", 465);
                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Host = "smtp.googlemail.com";
                smtpClient.Port = 587;
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Credentials = new System.Net.NetworkCredential("wooods-info@compuboot.in", "Wooods123");
                smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtpClient.EnableSsl = true;
                MailMessage mail = new MailMessage();

                //Setting From , To and CC
                mail.From = new MailAddress("wooods-info@compuboot.in", "Wooods BV.");
                mail.To.Add(_objModelMail.To);
                mail.Subject = _objModelMail.Subject;
                string Body = _objModelMail.Body;
                mail.Body = Body;
                mail.IsBodyHtml = true;


                /*smtpClient.Send(mail);
                MailMessage mail = new MailMessage();
                mail.To.Add(_objModelMail.To);
                //mail.From = new MailAddress(_objModelMail.From);
                mail.Subject = _objModelMail.Subject;
                string Body = _objModelMail.Body;
                mail.Body = Body;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential
                ("wooods@compuboot.in", "Wooods1234");// Enter seders User name and password
                smtp.EnableSsl = true;
                smtp.Send(mail);
                return View("mailtest   ", _objModelMail);
                ("wooods@gmail.com", "Wooods1234");// Enter seders User name and password
                smtp.EnableSsl = true;*/
                smtpClient.Send(mail);
                return View("mailtest", _objModelMail);

            }
            else
            {
                return View();
            }
        }

        public ActionResult Contact()
        {

            return View();
        }
        [HttpPost]
        public ViewResult Contact(WebWinkelGroep5.Models.MailModel _objModelMail)
        {
            if (ModelState.IsValid)
            {
                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Host = "smtp.googlemail.com";
                smtpClient.Port = 587;
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Credentials = new System.Net.NetworkCredential("wooods-info@compuboot.in", "Wooods123");
                smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtpClient.EnableSsl = true;
                MailMessage mail = new MailMessage();

                //Setting From , To and CC
                mail.From = new MailAddress(_objModelMail.From);
                mail.To.Add("wooods-info@compuboot.in");
                mail.Subject = _objModelMail.Subject;
                string Body = _objModelMail.Body;
                mail.Body = mail.From + "<br><br>" + Body;
                mail.IsBodyHtml = true;

                smtpClient.Send(mail);
                return View("Contact", _objModelMail);
            }
            else
            {
                return View();
            }
        }
    }
}

WebWinkelGroep5/WebWinkelGroep5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Wooods</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title"><img src="~/Images/logo.png" href="~/" /> @Html.ActionLink("Wooods", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <form action="~/product/searchproduct" method="post" id="searchform" name="searchform">
                    <input type="text" name="Zoeken" id="Zoeken" onkeypress="handle" />

                </form>
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu" style="float:left">
                        <li>@Html.ActionLink("Wooods", "Index", "Home")</li>
                        <li><a href="~/Product/">Producten</a></li>
                        <li><a href="~/winkelmand/viewmand">Winkelmand</a></li>
                        <li>@Html.ActionLink("Over ons", "About", "Home")</li>
                        <li><a href="~/Home/Werknemers">Werknemers</a></li>
                        <li>@Html.ActionLink("Contact", "Contact", "SendMailer")</li>
                        <li><a href="~/Home/TOS">Algemene voorwaarden</a></li>
                        <li><a href="~/Home/Disclaimer">Disclaimer</a></li>


                        @{
                            if (Session["isAdmin"] != null)
                            {
                                if ((bool)Session["isAdmin"])
                                {
                                    <li><a href="~/Admin/">Admin panel</a></li>
                                }
                            }
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Wooods B.V.</p>
            </div>
        </div>
    </footer>
    <script src="http://crypto-js.googlecode.com/svn/tags/3.0.2/build/rollups/md5.js"></script>
    @Scripts.Render("~/bundles/jquery")
    <script>
    function handle(e) {
        if (e.keyCode === 13) {
            document.getElementById("searchform").submit();
        }

        return false;
    }
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>